spring:
  application:
    name: StreamCutProject
  profiles:
    default: local
  servlet:
    multipart:
      max-file-size: ${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE:512MB}
      max-request-size: ${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE:520MB}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
  sql:
    init:
      mode: never
