package com.peatroxd.streamcutproject.vodjob;

public enum JobStatus {
    NEW,
    QUEUED_FOR_DOWNLOAD,
    DOWNLOADING,
    QUEUED_FOR_PROCESSING,
    EXTRACTING_AUDIO,
    TRANSCRIBING,
    DETECTING_SILENCE,
    ANALYZING_WINDOWS,
    GENERATING_CANDIDATES,
    READY_FOR_REVIEW,
    EXPORTING_CLIP,
    COMPLETED,
    CANCELED,
    FAILED
}
